title: Hayat Khan
logo: /assets/profile_pic.png
#description: Research Assistant @ Kansas State Univeristy, Manhttan, KS 66506, USA
show_downloads: true
theme: jekyll-theme-minimal

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: lkeselman@gmail.com
  facebook:
  flickr:
  github: leonidk
  instagram: leo_nid_k
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter:
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/
